version: '3.8'
services:
  app:
    build: .
    container_name: my-app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - compose-bridge

  redis:
    image: redis
    container_name: db-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - compose-bridge
networks:
  compose-bridge:
    driver: bridge